### ISSUE TITLE
Automatically display body part when entering 'Pose Ref Index' in 'Data Organization' tab 

### ISSUE THREAD

**Issue by katiekly** [catalystneuro/vame-desktop#12]
In the Data Organization Tab, we would like the body part to automatically display when the user enters indices in the 'Pose Ref Index' textbox. This will allow the user to be confident they chose the correct indices for egocentric alignment. 

The body part value can be found in the input CSV files. Body part columns will always be the same for each session and will always have 3 columns per body part.

**Comment by garrettmflynn** [comment]
Thank you for the detailed description @katiekly! In case I don't get to this before I leave, I'll flag that we should probably load the list of available body parts when running `Pipeline.load` (the `/load` endpoint on the backend) for easy reference. 

That way, this is always accessible on any page when the project is loaded.

Dynamically rendering the two selected body parts next to the `DynamicForm` input may be somewhat more complicated. I'm not 100% sure how to achieve this easily with React.

**Comment by nathan-vm** [comment]
@katiekly Hi, I'm the new frontend for the project. I took a look and, as Garrett said, these inputs are built based on a dynamic form created from a JSON schema, just like all the other input fields. Is there a chance we can just add a fixed description of body parts in this specific entry?

If so, I'll add this right now

![Captura de Tela 2024-06-14 às 15 02 28](https://github.com/catalystneuro/vame-desktop/assets/54302847/c180b13b-c886-4023-8f4a-110c4b63ad9e)

**Comment by katiekly** [comment]
Hi @nathan-vm, nice to meet you! Yes this could also work.
