### ISSUE TITLE
Review Node.js section of README

### ISSUE THREAD

**Issue by katiekly** [catalystneuro/vame-desktop#46]
In the README, we are unsure what this sentence means and whether it is necessary for end users to know this. This might add confusion for them. Let's meet to discuss what this sentence entails.

- This only needs to be run once at project initialization and when the `package.json` dependencies are updated.

**Comment by nathan-vm** [comment]
@katiekly This section is only if you want change the vame-desktop source code, in other words, for developers only.

This is for all instructions bellow this title :
- [x] Python
- [x] Node.js
- [x] Running the App
- [x] Build
- [x] Deploy

![Captura de Tela 2024-08-16 às 12 27 24](https://github.com/user-attachments/assets/caa4c2df-2b2d-4cbd-a816-810c8857ef26)
