### ISSUE TITLE
format changes for 'Edit Project' tab

### ISSUE THREAD

**Issue by katiekly** [catalystneuro/vame-desktop#5]
On this page, we'd like to have the parameters split into two categories: 'Main Configurations' and ' Advanced Configurations', where the all the 'Main Configuration' parameters will be displayed and the 'Advanced Configurations' parameters would be hidden. The 'Advanced Configurations' parameters can be displayed by clicking on the 'Advanced Configurations' drop down arrow.

It'd also be nice to have descriptions of each parameter by including a small info icon for users to hover over to display the parameter description.

Below, I outlined how the parameters should be categorized and noted any specifications of a parameter.

Main Configurations:
- Project : Do not make this editable, should just display the full project name
- Egocentric Data
- n_cluster : default value set to 30
- pose_confidence : default value set to 0.99
- num_features : include note below textbox 'NOTE: Please set to # of annotation points * 2'
- time_window : include note below textbox 'NOTE: Please set to 1/2 of video fps'
- max_epochs
- z_dims
- IQR factor
- robust
- parameterization

Advanced Configurations:
- all the remaining parameters

**Comment by garrettmflynn** [comment]
Awesome. Thank you @katiekly!

**Comment by garrettmflynn** [comment]
@katiekly Has anyone on the team worked with [JSON Schema](https://json-schema.org/) before? I'll need the configuration file annotated with this—but, after that, I'll be able to automatically generate a form that applies all of these constraints and formatting options.

**Comment by garrettmflynn** [comment]
Got an outline started here if you wouldn't mind updating with additional values, as well as checking for accuracy: https://github.com/catalystneuro/vame-desktop/blob/main/src/schema/config.schema.json

**Comment by katiekly** [comment]
@garrettmflynn I've briefly worked with JSON a long time ago, I think I can figure it out with the template you created. Thanks for noting the difference in default values. The default values I mentioned before aligns with our pipeline/set-up, hence the difference from the default values you found in the VAME library. 

I'll go over the configurations parameters and submit a PR.
